export enum NotificationType {
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  SMTP_TEST = 'SMTP_TEST',
  REFUND_PROCESSED = 'REFUND_PROCESSED',
  NEW_BOOKING_RECEIVED = 'NEW_BOOKING_RECEIVED',
  BOOKING_CANCELLED_BY_GUEST = 'BOOKING_CANCELLED_BY_GUEST',
  OPS_TASKS_CREATED = 'OPS_TASKS_CREATED',
  MAINTENANCE_REQUEST_CREATED = 'MAINTENANCE_REQUEST_CREATED',
}
